files:
  path:

    winpicupload: files/images/
    winviupload: files/videos/
    winotherupload: files/others/
    #===============访问映射地址===================
    #    图片上传路径
    picupload: file:/Volumes/Data/Projects/java/storyMap/target/classes/files/images/
    #    视频上传路径
    viupload: file:/Volumes/Data/Projects/java/storyMap/target/classes/files/videos/
    #    其他文件上传路径
    otherupload: file:/Volumes/Data/Projects/java/storyMap/target/classes/files/others/
spring:
  datasource:
    url: jdbc:mysql://121.40.193.32:3306/storymap?serverTimezone=UTC